# Create a GitHub action to email a report from a file at 6 a.m. daily
# Use the send-email action from the GitHub Marketplace

name: Deploy app

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: 'Report'
          body: 'Report attached'
          to: ${{ secrets.EMAIL }}
          attachments: 'report.txt'